[plugin]
icon = "https://wu-clan.github.io/picx-images-hosting/logo/fba.svg"
summary = "AI 分组管理"
version = "0.1.0"
description = "用于管理 AI 资源分组及资源可见性"
author = "wu-clan"
tags = ["ai"]
database = ["mysql", "postgresql"]
depends_on = ["ai"]

[app]
router = ["v1"]
